<?php

/**
 * @file
 * Middleware SQL Driver module.
 */
use Drupal\middleware_sql_driver\MiddlewareCore\SQLConnectionDriver;
use Drupal\Core\Form\FormStateInterface;

function middleware_sql_driver_connection_driver_sql_alter(&$container)
{
    $driver = new SQLConnectionDriver(function ($x) {
        $return = middleware_core__get_driver($x);
        return $return;
    }, function ($source_name) {
        return middleware_sql_driver__get_settings($source_name);
    }, 'sql');

    $defs = middleware_sql_driver__get_entity_definitions_local();
    $driver->setEntities($defs);
    $container['sql'] = $driver;
}

function middleware_sql_driver__get_settings($key)
{
    $settings = new \stdClass();

    $settings->DSN = 'mysql:host=127.0.0.1;dbname=Main_One_EDD';
    $settings->Username = 'root';
    $settings->Password = 'nigeria';
    $settings->DatabaseType = 'mysql';

    return $settings;
}

function middleware_sql_driver_form_middleware_core_admin_settings_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state){
    
    $form = \Drupal::formBuilder()->getForm('Drupal\middleware_sql_driver\Form\ConfigurationForm', $form);
}

function middleware_sql_driver_form_middleware_core_object_settings_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state){
    
    $form = \Drupal::formBuilder()->getForm('Drupal\middleware_sql_driver\Form\ObjectListForm', $form);
}

function middleware_sql_driver_middleware_driver_list_alter(&$driver_list){
    $driver_list['sql_mssql'] = 'Microsoft SQL Server';
    $driver_list['sql_mysql'] = 'My SQL';
}

function middleware_sql_driver_middleware_driver_settings_template_alter($name, &$driver_list, $settings = []){
    if(in_array($name, ['sql_mssql', 'sql_mysql'])){
        $driver_list[$name] = [
            'name' => 'Microsoft SQL Server',
            'settings' => [
                'connection_string' =>  [
                    '#type' => 'textfield',
                    '#title' => ('Connection string'),
                    '#default_value' => isset($settings['connection_string'])?($settings['connection_string']):''
                ],
                
                'username' =>  [
                    '#type' => 'textfield',
                    '#title' => ('Username'),
                    '#default_value' => isset($settings['username'])?($settings['username']):''
                ],
                
                'password' =>  [
                    '#type' => 'password',
                    '#title' => ('Password'),
                    '#default_value' => isset($settings['password'])?($settings['password']):'',
                    '#attributes' => [
                        'value' => isset($settings['password'])?($settings['password']):''
                    ]
                ],
            ]
        ];    
    }
}

function middleware_sql_driver_middleware_driver_settings_template_validate_alter($name, $parent_hierachy, FormStateInterface $form_state = NULL){
    // if(in_array($name, ['sql_mssql', 'sql_mysql'])){
        // $username = implode('][', array_merge($parent_hierachy, ['username']));
        // drupal_set_message(print_r($parent_hierachy, true));
        // $form_state->setErrorByName($username, "{$name} - {$form_state->getValue(['settings', 'username'])}");
    // }
}

function middleware_sql_driver__get_cached_entity_definitions($targetDriver)
{
    $return = [];
    if ($targetDriver != 'sql') {
        $return = middleware_sql_driver__get_entity_definitions();
    }
    
    return $return;
}

function middleware_sql_driver__get_entity_definitions_local(){
    return middleware_sql_driver__get_entity_definitions(...func_get_args())['sql'];
}

/**
 * Returns all the entity definitions implemented in Dynamics AX.
 * @return type
 */
function middleware_sql_driver__get_entity_definitions()
{
    $config = \Drupal::service('config.factory')->getEditable('middleware_sql_driver.objects');
    
    $return = ['sql' => $config->get('sql')];    
    if(is_null($return['sql'])){ 
        $return = [
            'sql'=> [
                'customerinfo' => [
                    'internal_name' => 'CustomerDictionary'
                    , 'datasource' => 'default'
                    , 'fields' => [
                        'ID' => [
                            'preferred_name' => 'Id'
                            , 'type' => 'int'
                            , 'mandatory' => 1,
                        ]
                        , 'ParentAccountId' => [
                            'preferred_name' => 'ParentAccountId'
                            , 'type' => 'string'
                        ]
                        , 'GCID' => [
                            'preferred_name' => 'GCID'
                            , 'type' => 'string'
                            , 'mandatory' => 1
                            , 'relationship' => [
                                'local_field' => 'GCID'
                                , 'preferred_local_key_name' => 'GCID'
                                , 'remote_field' => 'GCID'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'account'
                                , 'remote_driver' => 'salesforce'
                            ]
                        ]
                        , 'Name' => [
                            'preferred_name' => 'Name'
                            , 'type' => 'string'
                            , 'mandatory' => 1
                        ]
                        , 'DateModified' => [
                            'preferred_name' => 'Modified'
                            , 'type' => 'datetime'
                        ]
                        , 'DateCreated' => [
                            'preferred_name' => 'Created'
                            , 'type' => 'datetime'
                        ]
                        , 'LocalId' => [
                            'preferred_name' => 'SystemKey'
                            , 'type' => 'string'
                        ]
                        , 'System' => [
                            'preferred_name' => 'System'
                            , 'type' => 'int'
                            , 'mandatory' => 1
                            , 'relationship' => [
                                'local_field' => 'System'
                                , 'preferred_local_key_name' => 'SystemId'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'system'
                            ]
                        ]
                        , 'Entity' => [
                            'preferred_name' => 'Entity'
                            , 'type' => 'int'
                            , 'mandatory' => 1
                            , 'relationship' => [
                                'local_field' => 'Entity'
                                , 'preferred_local_key_name' => 'EntityId'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'system_entity'
                            ]
                        ]
                        , '_Siblings' => [
                            'preferred_name' => 'Siblings'
                            , 'type' => 'detail'
                            , 'relationship' => [
                                'local_field' => 'GCID'
                                , 'remote_field' => 'GCID'
                                , 'remote_type' => 'child'
                                , 'remote_entity' => 'customerinfo'
                                , 'filter' => 'SystemId ne 3'
                            ]
                        ]
                        , '_RemedyInfo' => [
                            'preferred_name' => 'RemedyInformation'
                            , 'type' => 'detail'
                            , 'relationship' => [
                                'local_field' => 'SystemKey'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'account'
                                , 'remote_driver' => 'bmc_remedy'
                            ]
                        ]
                        , '_DynamicsAccountInformation' => [
                            'preferred_name' => 'RelatedDynamicsAccount'
                            , 'type' => 'detail'
                            , 'relationship' => [
                                'local_field' => 'SystemKey'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'cust_table'
                                , 'remote_driver' => 'dynamics'
                            ]
                        ]
                        , '_AdvancedInfo' => [
                            'preferred_name' => 'AdvancedInformation'
                            , 'type' => 'detail'
                            , 'relationship' => [
                                'local_field' => 'GCID'
                                , 'remote_field' => 'GCID'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'account'
                                , 'remote_driver' => 'salesforce'
                            ]
                        ]
                        , '_FinancialRootAccountInfo' => [
                            'preferred_name' => 'FinancialRootAccountInformation'
                            , 'type' => 'detail'
                            , 'relationship' => [
                                'local_field' => 'GCID'
                                , 'remote_field' => 'Customer'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'rootaccount'
                                , 'remote_driver' => 'dynamics_ax'
                            ]
                        ]
                        , '_Contacts' => [
                            'preferred_name' => 'Contacts'
                            , 'type' => 'detail'
                            , 'relationship' => [
                                'local_field' => 'SystemKey'
                                , 'remote_field' => 'Account'
                                , 'remote_type' => 'child'
                                , 'remote_entity' => 'contact'
                                , 'remote_driver' => 'salesforce'
                            ],
                        ]
                    ]
                ]
                , 'system_entity' => [
                    'internal_name' => 'SystemEntity'
                    , 'datasource' => 'default'
                    , 'fields' => [
                        'ID' => [
                            'preferred_name' => 'Id'
                            , 'type' => 'int'
                            , 'mandatory' => 1,
                        ]
                        , 'Name' => [
                            'preferred_name' => 'Name'
                            , 'type' => 'string'
                            , 'mandatory' => 1
                        ]
                        , 'MiddlewareDriver' => [
                            'preferred_name' => 'MiddlewareDriver'
                            , 'type' => 'string'
                            , 'mandatory' => 1
                        ]
                        , 'Modified' => [
                            'preferred_name' => 'Modified'
                            , 'type' => 'datetime'
                        ]
                        , 'Created' => [
                            'preferred_name' => 'Created'
                            , 'type' => 'datetime'
                        ]
                        , 'SystemId' => [
                            'preferred_name' => 'System'
                            , 'type' => 'int'
                            , 'mandatory' => 1
                            , 'relationship' => [
                                'local_field' => 'System'
                                , 'preferred_local_key_name' => 'SystemId'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'system'
                            ]
                        ]
                    ]
                ]
                , 'system' => [
                    'internal_name' => 'System'
                    , 'datasource' => 'default'
                    , 'fields' => [
                        'ID' => [
                            'preferred_name' => 'Id'
                            , 'type' => 'int'
                            , 'mandatory' => 1,
                        ]
                        , 'Name' => [
                            'preferred_name' => 'Name'
                            , 'type' => 'string'
                            , 'mandatory' => 1
                        ]
                        , 'Modified' => [
                            'preferred_name' => 'Modified'
                            , 'type' => 'datetime'
                        ]
                        , 'Created' => [
                            'preferred_name' => 'Created'
                            , 'type' => 'datetime'
                        ]
                        , '_Entities' => [
                            'preferred_name' => 'Entities'
                            , 'type' => 'detail'
                            , 'relationship' => [
                                'local_field' => 'Id'
                                , 'remote_field' => 'SystemId'
                                , 'remote_type' => 'child'
                                , 'remote_entity' => 'system_entity'
                            ]
                        ]
                    ]
                ]
                , 'syncherrorlog' => [
                    'internal_name' => 'SynchErrorLog'
                    , 'datasource' => 'default'
                    , 'fields' => [
                        'ID' => [
                            'preferred_name' => 'Id'
                            , 'type' => 'int'
                            , 'mandatory' => 1,
                        ]
                        , 'Name' => [
                            'preferred_name' => 'Name'
                            , 'type' => 'string'
                        ]
                        , 'EntityName' => [
                            'preferred_name' => 'EntityName'
                            , 'type' => 'string'
                        ]
                        , 'Details' => [
                            'preferred_name' => 'Details'
                            , 'type' => 'string'
                        ]
                        , 'FileName' => [
                            'preferred_name' => 'FileName'
                            , 'type' => 'string'
                        ]
                        , 'LineNumber' => [
                            'preferred_name' => 'LineNumber'
                            , 'type' => 'string'
                        ]
                        , 'Modified' => [
                            'preferred_name' => 'Modified'
                            , 'type' => 'datetime'
                        ]
                        , 'Created' => [
                            'preferred_name' => 'Created'
                            , 'type' => 'datetime'
                        ]
                    ]
                ]
                , 'code_base' => [
                    'internal_name' => 'executable_code'
                    , 'manage_timestamps' => TRUE
                    , 'fields' => [
                        'id' => [
                            'preferred_name' => 'Id'
                            , 'type' => 'int'
                            , 'mandatory' => 1,
                        ]
                        , 'created' => [
                            'preferred_name' => 'Created'
                            , 'type' => 'datetime'
                        ]
                        , 'modified' => [
                            'preferred_name' => 'Modified'
                            , 'type' => 'datetime'
                        ]
                        , 'createdby' => [
                            'preferred_name' => 'CreatedBy'
                            , 'type' => 'string'
                            , 'relationship' => [
                                'local_field' => 'CreatedBy'
                                , 'preferred_local_key_name' => 'CreatedById'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'objects'
                                , 'remote_driver' => 'ldap'
                            ]
                        ]
                        , 'modifiedby' => [
                            'preferred_name' => 'ModifiedBy'
                            , 'type' => 'string'
                            , 'relationship' => [
                                'local_field' => 'ModifiedBy'
                                , 'preferred_local_key_name' => 'ModifiedById'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'objects'
                                , 'remote_driver' => 'ldap'
                            ]
                        ]
                        , 'name' => [
                            'preferred_name' => 'Name'
                            , 'type' => 'string'
                        ]
                        , 'disabled' => [
                            'preferred_name' => 'IsDisabled'
                            , 'type' => 'boolean'
                        ]
                        , 'status' => [
                            'preferred_name' => 'Status'
                            , 'type' => 'string'
                        ]
                        , 'description' => [
                            'preferred_name' => 'Description'
                            , 'type' => 'string'
                        ]
                        , 'logic' => [
                            'preferred_name' => 'Logic'
                            , 'type' => 'string'
                            , 'type_description' => 'MAX'
                        ]
                        , 'wsdl' => [
                            'preferred_name' => 'WSDL'
                            , 'type' => 'string'
                            , 'type_description' => 'MAX'
                        ]
                        , 'url' => [
                            'preferred_name' => 'URL'
                            , 'type' => 'string'
                            , 'type_description' => '1024'
                        ]
                        , 'service_type' => [
                            'preferred_name' => 'Type'
                            , 'type' => 'string'
                            , 'type_description' => '255'
                        ]
                        , 'version' => [
                            'preferred_name' => 'Version'
                            , 'type' => 'string'
                        ]
                        , 'frequency' => [
                            'preferred_name' => 'Frequency'
                            , 'type' => 'int'
                        ]
                        , 'enable_scheduling' => [
                            'preferred_name' => 'EnableScheduling'
                            , 'type' => 'boolean'
                        ]
                        , 'next_run' => [
                            'preferred_name' => 'NextRun'
                            , 'type' => 'datetime'
                        ]
                        , 'default_parameter' => [
                            'preferred_name' => 'DefaultParameter'
                            , 'type' => 'string'
                            , 'type_description' => 'MAX'
                        ]
                        , 'default_parameter_type' => [
                            'preferred_name' => 'DefaultParameterType'
                            , 'type' => 'string'
                            , 'type_description' => '255'
                        ]
                        , 'api_name' => [
                            'preferred_name' => 'APIName'
                            , 'type' => 'string'
                        ]
                        , '_Projects' => [
                            'preferred_name' => 'Projects'
                            , 'type' => 'detail'
                            , 'relationship' => [
                                'local_field' => 'Id'
                                , 'remote_field' => 'FunctionId'
                                , 'remote_type' => 'child'
                                , 'remote_entity' => 'dev_projects_function_map'
                            ]
                        ]
                    ]
                ]
                , 'scoms_inflow_staging_area' => [
                    'internal_name' => 'scoms_inflow_staging'
                    , 'manage_timestamps' => TRUE
                    , 'fields' => [
                        'id' => [
                            'preferred_name' => 'Id'
                            , 'type' => 'string'
                            , 'mandatory' => 1,
                        ]
                        , 'created' => [
                            'preferred_name' => 'Created'
                            , 'type' => 'datetime'
                        ]
                        , 'modified' => [
                            'preferred_name' => 'Modified'
                            , 'type' => 'datetime'
                        ]
                        , 'createdby' => [
                            'preferred_name' => 'CreatedBy'
                            , 'type' => 'string'
                            , 'relationship' => [
                                'local_field' => 'CreatedBy'
                                , 'preferred_local_key_name' => 'CreatedById'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'objects'
                                , 'remote_driver' => 'ldap'
                            ]
                        ]
                        , 'modifiedby' => [
                            'preferred_name' => 'ModifiedBy'
                            , 'type' => 'string'
                            , 'relationship' => [
                                'local_field' => 'ModifiedBy'
                                , 'preferred_local_key_name' => 'ModifiedById'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'objects'
                                , 'remote_driver' => 'ldap'
                            ]
                        ]
                        , 'sales_id' => [
                            'preferred_name' => 'SalesId'
                            , 'type' => 'string'
                        ]
                        , 'invoice_id' => [
                            'preferred_name' => 'InvoiceId'
                            , 'type' => 'string'
                        ]
                        , 'customer_id' => [
                            'preferred_name' => 'Customer'
                            , 'type' => 'string'
                            , 'relationship' => [
                                'local_field' => 'Customer'
                                , 'preferred_local_key_name' => 'CustomerId'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'account'
                                , 'remote_driver' => 'salesforce'
                            ]
                        ]
                        , 'customer_name' => [
                            'preferred_name' => 'CustomerName'
                            , 'type' => 'string'
                        ]
                        , 'year' => [
                            'preferred_name' => 'Year'
                            , 'type' => 'int'
                        ]
                        , 'quarter' => [
                            'preferred_name' => 'Quarter'
                            , 'type' => 'int'
                        ]
                        , 'status_comment' => [
                            'preferred_name' => 'StatusComment'
                            , 'type' => 'string'
                            , 'type_description' => 'max'
                        ]
                        , 'narrative' => [
                            'preferred_name' => 'Narrative'
                            , 'type' => 'string'
                            , 'type_description' => 'max'
                        ]
                        , 'cash_inflow_id' => [
                            'preferred_name' => 'CashInflow'
                            , 'type' => 'string'
                            , 'relationship' => [
                                'local_field' => 'CashInflow'
                                , 'preferred_local_key_name' => 'CashInflowId'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'cash_inflow'
                                , 'remote_driver' => 'salesforce'
                            ]
                        ]
                        , 'payment_date' => [
                            'preferred_name' => 'PaymentDate'
                            , 'type' => 'date'
                        ]
                        , 'due_date' => [
                            'preferred_name' => 'DueDate'
                            , 'type' => 'date'
                        ]
                        , 'amount' => [
                            'preferred_name' => 'Amount'
                            , 'type' => 'decimal'
                            , 'type_description' => '16,2'
                        ]
                        , 'currency' => [
                            'preferred_name' => 'Currency'
                            , 'type' => 'string'
                        ]
                        , 'exchange_rate' => [
                            'preferred_name' => 'ExchangeRate'
                            , 'type' => 'decimal'
                            , 'type_description' => '16,2'
                        ]
                        , 'sent_to_scoms' => [
                            'preferred_name' => 'SentToSCOMS'
                            , 'type' => 'int'
                        ]
                    ]
                ]
                , 'netboss_circuit_interface_mapping' => [
                    'internal_name' => 'NetBoss_Circuit_Interface_Mapping'
                    , 'manage_timestamps' => TRUE
                    , 'fields' => [
                        'id' => [
                            'preferred_name' => 'Id'
                            , 'type' => 'string'
                            , 'mandatory' => 1,
                        ]
                        , 'created' => [
                            'preferred_name' => 'Created'
                            , 'type' => 'datetime'
                        ]
                        , 'modified' => [
                            'preferred_name' => 'Modified'
                            , 'type' => 'datetime'
                        ]
                        , 'createdby' => [
                            'preferred_name' => 'CreatedBy'
                            , 'type' => 'string'
                            , 'relationship' => [
                                'local_field' => 'CreatedBy'
                                , 'preferred_local_key_name' => 'CreatedById'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'objects'
                                , 'remote_driver' => 'ldap'
                            ]
                        ]
                        , 'modifiedby' => [
                            'preferred_name' => 'ModifiedBy'
                            , 'type' => 'string'
                            , 'relationship' => [
                                'local_field' => 'ModifiedBy'
                                , 'preferred_local_key_name' => 'ModifiedById'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'objects'
                                , 'remote_driver' => 'ldap'
                            ]
                        ]
                        , 'DeviceName' => [
                            'preferred_name' => 'DeviceName'
                            , 'type' => 'string'
                        ]
                        , 'ObjectName' => [
                            'preferred_name' => 'ObjectName'
                            , 'type' => 'string'
                        ]
                        , 'ObjectDescription' => [
                            'preferred_name' => 'ObjectDescription'
                            , 'type' => 'string'
                            , 'type_description' => 'MAX'
                        ]
                        , 'CircuitID' => [
                            'preferred_name' => 'CustomerProduct'
                            , 'type' => 'string'
                            , 'relationship' => [
                                'local_field' => 'CustomerProduct'
                                , 'preferred_local_key_name' => 'CircuitID'
                                , 'remote_field' => 'Name'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'customer_product'
                                , 'remote_driver' => 'salesforce'
                            ]
                        ]
                        , 'TrafficInMax' => [
                            'preferred_name' => 'MaxTrafficIn'
                            , 'type' => 'decimal'
                            , 'type_description' => '16,2'
                        ]
                        , 'TrafficOutMax' => [
                            'preferred_name' => 'MaxTrafficOut'
                            , 'type' => 'decimal'
                            , 'type_description' => '16,2'
                        ]
                        , 'CIRMbps' => [
                            'preferred_name' => 'CIR'
                            , 'type' => 'string'
                        ]
                        , 'PIRMbps' => [
                            'preferred_name' => 'PIR'
                            , 'type' => 'string'
                        ]
                    ]
                ]
                , 'rest_endpoints' => [
                    'internal_name' => 'RESTEndPoints'
                    , 'manage_timestamps' => TRUE
                    , 'fields' => [
                        'id' => [
                            'preferred_name' => 'Id'
                            , 'type' => 'string'
                            , 'mandatory' => 1,
                        ]
                        , 'created' => [
                            'preferred_name' => 'Created'
                            , 'type' => 'datetime'
                        ]
                        , 'modified' => [
                            'preferred_name' => 'Modified'
                            , 'type' => 'datetime'
                        ]
                        , 'createdby' => [
                            'preferred_name' => 'CreatedBy'
                            , 'type' => 'string'
                            , 'relationship' => [
                                'local_field' => 'CreatedBy'
                                , 'preferred_local_key_name' => 'CreatedById'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'objects'
                                , 'remote_driver' => 'ldap'
                            ]
                        ]
                        , 'modifiedby' => [
                            'preferred_name' => 'ModifiedBy'
                            , 'type' => 'string'
                            , 'relationship' => [
                                'local_field' => 'ModifiedBy'
                                , 'preferred_local_key_name' => 'ModifiedById'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'objects'
                                , 'remote_driver' => 'ldap'
                            ]
                        ]
                        , 'name' => [
                            'preferred_name' => 'Name'
                            , 'type' => 'string'
                        ]
                        , 'disabled' => [
                            'preferred_name' => 'IsDisabled'
                            , 'type' => 'boolean'
                        ]
                        , 'description' => [
                            'preferred_name' => 'Description'
                            , 'type' => 'string'
                        ]
                        , 'version' => [
                            'preferred_name' => 'Version'
                            , 'type' => 'string'
                        ]
                        , 'api_name' => [
                            'preferred_name' => 'APIName'
                            , 'type' => 'string'
                        ]
                        , 'script' => [
                            'preferred_name' => 'Logic'
                            , 'type' => 'string'
                            , 'type_description' => 'MAX'
                        ]
                        , 'url' => [
                            'preferred_name' => 'URL'
                            , 'type' => 'string'
                            , 'type_description' => '1024'
                        ]
                    ]
                ]
                , 'dev_projects' => [
                    'internal_name' => 'Development_Projects'
                    , 'manage_timestamps' => TRUE
                    , 'fields' => [
                        'id' => [
                            'preferred_name' => 'Id'
                            , 'type' => 'string'
                            , 'mandatory' => 1,
                        ]
                        , 'created' => [
                            'preferred_name' => 'Created'
                            , 'type' => 'datetime'
                        ]
                        , 'modified' => [
                            'preferred_name' => 'Modified'
                            , 'type' => 'datetime'
                        ]
                        , 'createdby' => [
                            'preferred_name' => 'CreatedBy'
                            , 'type' => 'string'
                            , 'relationship' => [
                                'local_field' => 'CreatedBy'
                                , 'preferred_local_key_name' => 'CreatedById'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'objects'
                                , 'remote_driver' => 'ldap'
                            ]
                        ]
                        , 'modifiedby' => [
                            'preferred_name' => 'ModifiedBy'
                            , 'type' => 'string'
                            , 'relationship' => [
                                'local_field' => 'ModifiedBy'
                                , 'preferred_local_key_name' => 'ModifiedById'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'objects'
                                , 'remote_driver' => 'ldap'
                            ]
                        ]
                        , 'name' => [
                            'preferred_name' => 'Name'
                            , 'type' => 'string'
                        ]
                        , 'description' => [
                            'preferred_name' => 'Description'
                            , 'type' => 'string'
                        ]
                        , '_Functions' => [
                            'preferred_name' => 'Functions'
                            , 'type' => 'detail'
                            , 'relationship' => [
                                'local_field' => 'Id'
                                , 'remote_field' => 'ProjectId'
                                , 'remote_type' => 'child'
                                , 'remote_entity' => 'dev_projects_function_map'
                            ]
                        ]
                    ]
                ]
                , 'dev_projects_function_map' => [
                    'internal_name' => 'Development_Projects_Function_Map'
                    , 'manage_timestamps' => TRUE
                    , 'fields' => [
                        'id' => [
                            'preferred_name' => 'Id'
                            , 'type' => 'int'
                            , 'mandatory' => 1,
                        ]
                        , 'created' => [
                            'preferred_name' => 'Created'
                            , 'type' => 'datetime'
                        ]
                        , 'modified' => [
                            'preferred_name' => 'Modified'
                            , 'type' => 'datetime'
                        ]
                        , 'createdby' => [
                            'preferred_name' => 'CreatedBy'
                            , 'type' => 'string'
                            , 'relationship' => [
                                'local_field' => 'CreatedBy'
                                , 'preferred_local_key_name' => 'CreatedById'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'objects'
                                , 'remote_driver' => 'ldap'
                            ]
                        ]
                        , 'modifiedby' => [
                            'preferred_name' => 'ModifiedBy'
                            , 'type' => 'string'
                            , 'relationship' => [
                                'local_field' => 'ModifiedBy'
                                , 'preferred_local_key_name' => 'ModifiedById'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'objects'
                                , 'remote_driver' => 'ldap'
                            ]
                        ]
                        ,'projectid' => [
                            'preferred_name' => 'Project'
                            , 'type' => 'string'
                            , 'relationship' => [
                                'local_field' => 'Project'
                                , 'preferred_local_key_name' => 'ProjectId'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'dev_projects'
                            ]
                        ]
                        , 'functionid' => [
                            'preferred_name' => 'Function'
                            , 'type' => 'string'
                            , 'relationship' => [
                                'local_field' => 'Function'
                                , 'preferred_local_key_name' => 'FunctionId'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'code_base'
                            ]
                        ]
                    ]
                ]
                , 'mail_endpoints' => [
                    'internal_name' => 'MailEndPoints'
                    , 'manage_timestamps' => TRUE
                    , 'fields' => [
                        'id' => [
                            'preferred_name' => 'Id'
                            , 'type' => 'string'
                            , 'mandatory' => 1,
                        ]
                        , 'created' => [
                            'preferred_name' => 'Created'
                            , 'type' => 'datetime'
                        ]
                        , 'modified' => [
                            'preferred_name' => 'Modified'
                            , 'type' => 'datetime'
                        ]
                        , 'createdby' => [
                            'preferred_name' => 'CreatedBy'
                            , 'type' => 'string'
                            , 'relationship' => [
                                'local_field' => 'CreatedBy'
                                , 'preferred_local_key_name' => 'CreatedById'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'objects'
                                , 'remote_driver' => 'ldap'
                            ]
                        ]
                        , 'modifiedby' => [
                            'preferred_name' => 'ModifiedBy'
                            , 'type' => 'string'
                            , 'relationship' => [
                                'local_field' => 'ModifiedBy'
                                , 'preferred_local_key_name' => 'ModifiedById'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'objects'
                                , 'remote_driver' => 'ldap'
                            ]
                        ]
                        , 'name' => [
                            'preferred_name' => 'Name'
                            , 'type' => 'string'
                        ]
                        , 'status' => [
                            'preferred_name' => 'Status'
                            , 'type' => 'string'
                        ]
                        , 'description' => [
                            'preferred_name' => 'Description'
                            , 'type' => 'string'
                            , 'type_description' => 'MAX'
                        ]
                        , 'logic' => [
                            'preferred_name' => 'Logic'
                            , 'type' => 'string'
                            , 'type_description' => 'MAX'
                        ]
                        , 'sender' => [
                            'preferred_name' => 'Sender'
                            , 'type' => 'string'
                            , 'length' => '1024'
                        ]
                        , 'is_pulled' => [
                            'preferred_name' => 'IsPulled'
                            , 'type' => 'boolean'
                        ]
                        , 'next_pull' => [
                            'preferred_name' => 'NextPull'
                            , 'type' => 'datetime'
                        ]
                    ]
                ]        
                , 'contract_term' => [
                    'internal_name' => 'Contract_Term'
                    , 'manage_timestamps' => TRUE
                    // , 'delegate_to' => 'sql'
                    // , 'cache_freq' => 60
                    , 'fields' => [
                        'Title__c' => [
                            'preferred_name' => 'Title'
                            , 'type' => 'string'
                            , 'mandatory' => 1,
                        ]
                        , 'Type__c' => [
                            'preferred_name' => 'Type'
                            , 'type' => 'string'
                        ]
                        , 'LastModifiedDate' => [
                            'preferred_name' => 'Modified'
                            , 'type' => 'datetime'
                        ]
                        , 'CreatedDate' => [
                            'preferred_name' => 'Created'
                            , 'type' => 'datetime'
                        ]
                        , 'Id' => [
                            'preferred_name' => 'Id'
                            , 'type' => 'int'
                            , 'mandatory' => 1
                        ]
                        , 'Description__c' => [
                            'preferred_name' => 'Description'
                            , 'type' => 'string'
                            , 'type_description' => 'MAX'
                        ]
                        , 'ServiceGroup' => [
                            'preferred_name' => 'ServiceGroup'
                            , 'type' => 'string'
                            , 'type_description' => '255'
                        ]
                        , 'BusinessEntity' => [
                            'preferred_name' => 'BusinessEntity'
                            , 'type' => 'string'
                            , 'type_description' => '255'
                        ]
                        , 'Weight__c' => [
                            'preferred_name' => 'Weight'
                            , 'type' => 'int'
                        ]
                        , 'IsGeneric__c' => [
                            'preferred_name' => 'IsGeneric'
                            , 'type' => 'boolean',
                        ]
                        , 'IsDeleted' => [
                            'preferred_name' => 'IsDeleted'
                            , 'type' => 'boolean',
                        ]
                        , 'CreatedById' => [
                            'preferred_name' => 'CreatedBy'
                            , 'type' => 'string'
                            , 'relationship' => [
                                'local_field' => 'CreatedBy'
                                , 'preferred_local_key_name' => 'CreatedById'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'user'
                            ]
                        ]
                        , 'LastModifiedById' => [
                            'preferred_name' => 'ModifiedBy'
                            , 'type' => 'string'
                            , 'relationship' => [
                                'local_field' => 'ModifiedBy'
                                , 'preferred_local_key_name' => 'ModifiedById'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'user'
                            ]
                        ]
                        , '_SubTerms' => [
                            'preferred_name' => 'SubTerms'
                            , 'type' => 'detail'
                            , 'relationship' => [
                                'local_field' => 'Id'
                                , 'remote_field' => 'ParentTermId'
                                , 'remote_type' => 'child'
                                , 'remote_entity' => 'contract_term'
                                , 'filter' => 'IsDeleted eq $false$'
                            ],
                        ]
                    ]
                ]
                , 'sale_contract_term' => [
                    'internal_name' => 'Sale_Contract_Term'
                    , 'manage_timestamps' => TRUE
                    // , 'delegate_to' => 'sql'
                    // , 'cache_freq' => 60
                    , 'fields' => [
                        'Title__c' => [
                            'preferred_name' => 'Title'
                            , 'type' => 'string'
                        ]
                        , 'Type__c' => [
                            'preferred_name' => 'Type'
                            , 'type' => 'string'
                        ]
                        , 'LastModifiedDate' => [
                            'preferred_name' => 'Modified'
                            , 'type' => 'datetime'
                        ]
                        , 'CreatedDate' => [
                            'preferred_name' => 'Created'
                            , 'type' => 'datetime'
                        ]
                        , 'Id' => [
                            'preferred_name' => 'Id'
                            , 'type' => 'int'
                            , 'mandatory' => 1,
                        ]
                        , 'Custom_Description__c' => [
                            'preferred_name' => 'AdditionalDescription'
                            , 'type' => 'string'
                            , 'type_description' => 'MAX'
                        ]
                        , 'Weight__c' => [
                            'preferred_name' => 'Weight'
                            , 'type' => 'int'
                        ]
                        , 'IsDeleted' => [
                            'preferred_name' => 'IsDeleted'
                            , 'type' => 'boolean',
                        ]
                        , 'Opportunity__c' => [
                            'preferred_name' => 'Opportunity'
                            , 'type' => 'string'
                            , 'relationship' => [
                                'local_field' => 'Opportunity'
                                , 'preferred_local_key_name' => 'OpportunityId'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'opportunity'
                                , 'remote_driver' => 'salesforce'
                            ]
                        ]
                        , 'Contract_Term__c' => [
                            'preferred_name' => 'ReferencedContractTerm'
                            , 'type' => 'int'
                            , 'relationship' => [
                                'local_field' => 'ReferencedContractTerm'
                                , 'preferred_local_key_name' => 'ReferencedContractTermId'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'contract_term'
                                , 'remote_driver' => 'sql'
                            ]
                        ]
                        , 'CreatedById' => [
                            'preferred_name' => 'CreatedBy'
                            , 'type' => 'string'
                            , 'relationship' => [
                                'local_field' => 'CreatedBy'
                                , 'preferred_local_key_name' => 'CreatedById'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'user'
                            ]
                        ]
                        , 'LastModifiedById' => [
                            'preferred_name' => 'ModifiedBy'
                            , 'type' => 'string'
                            , 'relationship' => [
                                'local_field' => 'ModifiedBy'
                                , 'preferred_local_key_name' => 'ModifiedById'
                                , 'remote_field' => 'Id'
                                , 'remote_type' => 'parent'
                                , 'remote_entity' => 'user'
                            ]
                        ]
                    ]
                ]
            ]
        ];

        $config->setData($return)->save();
    }

    // Add other entities that have been cached to this driver.
    $cached_all = Drupal::moduleHandler()->invokeAll('_get_cached_entity_definitions', ['sql']);
    foreach ($cached_all as $cached) {
        $g = is_null($cached)?[]:$cached;
        $return['sql'] = array_merge($return['sql'], $g);
    }

    $all_delegated = Drupal::moduleHandler()->invokeAll('_get_delegated_entity_definitions', ['sql']);
    foreach ($all_delegated as $delegated) {
        $g = is_null($delegated)?[]:$delegated;
        $return['sql'] = array_merge($return['sql'], $g);
    }

    return $return;
}